name: NPM Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_check:
    name: Lint and Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install buf
        run: |
        BIN="/usr/local/bin" && \
        VERSION="0.33.0" && \
        BINARY_NAME="buf" && \
          curl -sSL \
            "https://github.com/bufbuild/buf/releases/download/v${VERSION}/${BINARY_NAME}-$(uname -s)-$(uname -m)" \
            -o "${BIN}/${BINARY_NAME}" && \
          chmod +x "${BIN}/${BINARY_NAME}"
      - name: Run checks
        run: |
          make check

  publish:
    needs: test
    name: Build
    if: github.head_ref == null # head_ref won't be null for Pull Request builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: semver_tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
      - name: Publish Node NPM package
        env:
          VERSION: ${{ steps.semver_tag.outputs.new_tag }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./node
        run: |
          npm --no-git-tag-version version ${VERSION}
          echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish
      - name: Publish GRPCWeb NPM package
        env:
          VERSION: ${{ steps.semver_tag.outputs.new_tag }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./grpcweb
        run: |
          npm --no-git-tag-version version ${VERSION}
          echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish
